### ISSUE TITLE
YAML config doesn't work, converting it to JSON does work

### ISSUE THREAD

**Issue by HunterAP23** [sat3ll/waifu2x-ncnn-vulkan-flatpak#1]
Been trying to find a waifu2x program that had proper GPU acceleration for linux and came across this one. I cloned the project into a Docker container (windows hosts, ubuntu container), installed flatpak and followed the installation steps, but when running the build/install command, I'm met with this error:

```bash
Can't parse 'com.github.nihui.waifu2x-ncnn-vulkan.yaml': <data>:1:6: Parse error: unexpected identifier `app-id', expected value
```
I tried wrapping both the `api-id` key in quotes, as well as the value for it in separate quotes, but it refused to work.

I quickly looked up a YAML to JSON converter, since I saw flatpak supported both, then used the JSON file instead and it succeeds in building. I attached the converted file to this issue.

[YAML_as_JSON.txt](https://github.com/sat3ll/waifu2x-ncnn-vulkan-flatpak/files/3484887/YAML_as_JSON.txt)

**Comment by sat3ll** [comment]
what flatpak version?

**Comment by HunterAP23** [comment]
flatpak 1.0.8-0ubuntu0.18.04.1 amd64
flatpak-builder 0.10.9-1ubuntu1 amd64

**Comment by sat3ll** [comment]
Something must have changed with the more recent versions of flatpak-builder (at least as of 1.0.7).  
I seem to be unable to build it using the same files from here.  
Unfortunately I am away so I can't look into it for the meantime, will have to wait a while.

**Comment by sat3ll** [comment]
can't reproduce with flatpak-builder 1.0.9 @ fedora
