### ISSUE TITLE
Can't decode image

### ISSUE THREAD

**Issue by RyanHakurei** [sat3ll/waifu2x-ncnn-vulkan-flatpak#2]
For some reason this is all I get, period:
```
flatpak run com.github.nihui.waifu2x-ncnn-vulkan -i vlcsnap-2019-08-28-13h09m13s656.png -o vlcsnap-2019-08-28-13h09m13s656-Waifu2x.png -n -1 -s 2 -t 400
[0 Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2)]  queueC=0[1]  queueT=0[1]  memU=0  memDL=0  memHV=0
[0 Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2)]  fp16p=1  fp16s=1  fp16a=1  int8s=1  int8a=1
decode image vlcsnap-2019-08-28-13h09m13s656.png failed
```

The installed flatpak version is 1.4.2, host OS is Arch, and I enabled the filesystem override.

**Comment by sat3ll** [comment]
This type of error happens when the file is corrupt or if it can't access it.
Is this image located in home / **~** ? If so, try overriding it to home (`--filesystem=home`)

**Comment by RyanHakurei** [comment]
@sat3ll I did the override? Or do you have to do that every time you run it? I thought it was a permission type thing once you grant it that Flatpak has that permission until revoked.

**Comment by sat3ll** [comment]
It needs to be done only once. But right now, either it has trouble accessing that file (host doesn't allow every directory to be accessed iirc, check flatpak docs for more info) or that file is corrupt.

**Comment by RyanHakurei** [comment]
I worked around the issue by generating XDG dirs and just dropping the photos I wanted to work with in the ~/Pictures folder.
