### ISSUE TITLE
Submit in Flathub

### ISSUE THREAD

**Issue by TheEvilSkeleton** [sat3ll/waifu2x-ncnn-vulkan-flatpak#3]
FYI Flathub [accepts](https://discourse.flathub.org/t/cli-only-apps-on-flathub/1315/2) CLI applications. I think they'll accept this one in Flathub as well.

**Comment by sat3ll** [comment]
Supposing Flathub accepts this, it would remain hidden from the front page. Is it still worth submitting it?

**Comment by TheEvilSkeleton** [comment]
I personally think yes, because we can always submit an MR in waifu2x-ncnn-vulkan's README to inform the user that there are pre-built packages in the Flathub remote.

Although it's just my opinion.

**Comment by sat3ll** [comment]
Is there any changes that should be made before submitting?

**Comment by TheEvilSkeleton** [comment]
I went in the #flatpak IRC, and I got these comments:

> TheEvilSkeleton: No reason to use git-type x-checker-data when upstream publishes proper github releases. Use json-type x-checker-data instead.

> TheEvilSkeleton, if you're going to make a flatpak of this avoid having dashes at the end of the name incase you ever want to add extensions

**Comment by sat3ll** [comment]
Closing with https://github.com/flathub/com.github.nihui.waifu2x-ncnn-vulkan
